### ISSUE TITLE
Linkage error with Artifactory Docker Runner

### ISSUE THREAD

**Issue by hervestern** [jfrog/teamcity-artifactory-plugin#174]
**Context:**
TeamCity 2025.07.3 Build 197398
TeamCity Artifactory Plugin 2.11.0
JRE 17 (same error with JRE 21)

**Error on _docker push_:**
Build log extract:
```
14:14:02 Step 13/13: Docker Push (Artifactory Docker)
14:14:02   Build started.
14:14:02   Usage info sent successfully.
14:14:02   Pushing image: repository.inetpsa.com/mph09/api-middleware/apim:11.3.0
14:14:03   java.lang.UnsatisfiedLinkError: failed to load the required native library
14:14:03   java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: failed to load the required native library
    at org.jfrog.teamcity.agent.BaseArtifactoryBuildProcess.waitFor(BaseArtifactoryBuildProcess.java:148)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:61)
    ...
    Caused by: java.lang.NoSuchMethodError: Method io.netty.channel.unix.Socket.sendTo(IZLjava/nio/ByteBuffer;II[BII)I not found
      at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
      at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
      at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
      at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
      at java.base/java.lang.Runtime.load0(Runtime.java:852)
      at java.base/java.lang.System.load(System.java:2025)
      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
      ... 35 more
```

**Additional notes**
Was working with TeamCity 2024.12.

**Comment by austlane** [comment]
Experiencing the same on TeamCity 2024.11.2 + JRE 17. All ArtifactoryDocker steps are failing, requiring a revert to 2.10.3.

@naveenku-jfrog @bhanurp I'd suggest removing the 2.11.0 release until this can be fixed.

**Comment by stiwa-wrre** [comment]
Could someone of Jfrog have a look on this issue? I mean its now nearly have a year without a working version.
